spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_nice_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    com.francefootball.niceequipefootballapi: "debug"

security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 3600000
