spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_nice_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    com.francefootball.niceequipefootballapi: "debug"

security:
  jwt:
    secret-key: "K9ZC2Zwo7dnXbOs3gCKfEi6JoSevkWxzugAhByuZhPmbcrOUKJxOWuih1XD6FEg"
    expiration-time: 3600000
data:
  initialize:
    enabled: "true"
